lessons = {
    "Beginner Signs": {
        "brother": "https://example.com/videos/hello.mp4",
        "can": "https://example.com/videos/i_love_you.mp4",
        "come": "https://example.com/videos/return.mp4",
        "daughter": "https://example.com/videos/return.mp4",
        "drink": "https://example.com/videos/return.mp4",
        "eat": "https://example.com/videos/return.mp4",
        "friend": "https://example.com/videos/return.mp4",
        "go": "https://example.com/videos/return.mp4",
        "good": "https://example.com/videos/return.mp4",
        "hello": "https://example.com/videos/return.mp4",
        "mother": "https://example.com/videos/return.mp4",
        "name": "https://example.com/videos/return.mp4",
        "no": "https://example.com/videos/return.mp4",
        "please": "https://example.com/videos/return.mp4",
        "help": "https://example.com/videos/return.mp4",
        "sit": "https://example.com/videos/return.mp4",
        "sleep": "https://example.com/videos/return.mp4",
        "son": "https://example.com/videos/return.mp4",
        "thank you": "https://example.com/videos/return.mp4",
    },
    "Intermediate Signs": {
        "cannot": "https://example.com/videos/thank_you.mp4",
        "good morning": "https://example.com/videos/good_morning.mp4",
        "good evening": "https://example.com/videos/friend.mp4",
        "good afternoon": "https://example.com/videos/return.mp4",
        "good night": "https://example.com/videos/return.mp4",
        "you": "https://example.com/videos/return.mp4",
        "how many": "https://example.com/videos/return.mp4",
        "husband": "https://example.com/videos/return.mp4",
        "fine": "https://example.com/videos/return.mp4",
        "i dont understand": "https://example.com/videos/return.mp4",
        "like": "https://example.com/videos/return.mp4",
        "stand": "https://example.com/videos/return.mp4",
        "want": "https://example.com/videos/return.mp4",
        "what": "https://example.com/videos/return.mp4",
        "when": "https://example.com/videos/return.mp4",
        "where": "https://example.com/videos/return.mp4",
    },
    "Sentence Formation": {
        "Hello! How are you?": "https://example.com/videos/how_are_you.mp4",
        "Please help me eat!": "https://example.com/videos/i_am_fine.mp4",
        "I am thirsty, can you help me?": "https://example.com/videos/what_is_your_name.mp4",
        "My name is __, nice to meet you!": "https://example.com/videos/what_is_your_name.mp4",
        "Stop, I dont understand.": "https://example.com/videos/what_is_your_name.mp4",
        "I am sorry, I dont know.": "https://example.com/videos/what_is_your_name.mp4",
        "Thank you, I am fine.": "https://example.com/videos/what_is_your_name.mp4",
        "Wait for me, I will return from home.": "https://example.com/videos/what_is_your_name.mp4",
        "Good morning, I know you.": "https://example.com/videos/what_is_your_name.mp4",
        "Can you help me stand?": "https://example.com/videos/what_is_your_name.mp4",
        
    },
    "Quizzes": {
        "Beginner Quiz": "https://example.com/quizzes/beginner",
        "Intermediate Quiz": "https://example.com/quizzes/intermediate",
        "Sentence Quiz": "https://example.com/quizzes/sentence",
    }
}
